<?php

declare(strict_types=1);

namespace OneRedPaperclip\Tests\Unit\Entity;

use OneRedPaperclip\Entity\Challenge;
use OneRedPaperclip\Enum\ChallengeStatus;
use OneRedPaperclip\Enum\ChallengeVisibility;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

#[CoversClass(Challenge::class)]
final class ChallengeTest extends TestCase
{
    #[Test]
    public function entityTypeIdIsChallenge(): void
    {
        $challenge = new Challenge([]);

        $this->assertSame('challenge', $challenge->getEntityTypeId());
    }

    #[Test]
    public function newChallengeIsNew(): void
    {
        $challenge = new Challenge(['title' => 'Test']);

        $this->assertTrue($challenge->isNew());
    }

    #[Test]
    public function existingChallengeIsNotNew(): void
    {
        $challenge = new Challenge(['id' => 1, 'title' => 'Test']);

        $this->assertFalse($challenge->isNew());
    }

    #[Test]
    public function labelReturnsTitle(): void
    {
        $challenge = new Challenge(['title' => 'Red Paperclip']);

        $this->assertSame('Red Paperclip', $challenge->label());
    }

    #[Test]
    public function getTitleReturnsTitle(): void
    {
        $challenge = new Challenge(['title' => 'My Challenge']);

        $this->assertSame('My Challenge', $challenge->getTitle());
    }

    #[Test]
    public function setTitleUpdatesTitle(): void
    {
        $challenge = new Challenge(['title' => 'Old']);
        $challenge->setTitle('New');

        $this->assertSame('New', $challenge->getTitle());
    }

    #[Test]
    public function getSlugReturnsSlug(): void
    {
        $challenge = new Challenge(['title' => 'Test', 'slug' => 'my-challenge']);

        $this->assertSame('my-challenge', $challenge->getSlug());
    }

    #[Test]
    public function getStatusReturnsEnum(): void
    {
        $challenge = new Challenge(['title' => 'Test', 'status' => 'draft']);

        $this->assertSame(ChallengeStatus::Draft, $challenge->getStatus());
    }

    #[Test]
    public function setStatusUpdatesStatus(): void
    {
        $challenge = new Challenge(['title' => 'Test', 'status' => 'draft']);
        $challenge->setStatus(ChallengeStatus::Published);

        $this->assertSame(ChallengeStatus::Published, $challenge->getStatus());
    }

    #[Test]
    public function getVisibilityReturnsEnum(): void
    {
        $challenge = new Challenge(['title' => 'Test', 'visibility' => 'public']);

        $this->assertSame(ChallengeVisibility::Public, $challenge->getVisibility());
    }

    #[Test]
    public function defaultStatusIsDraft(): void
    {
        $challenge = new Challenge(['title' => 'Test']);

        $this->assertSame(ChallengeStatus::Draft, $challenge->getStatus());
    }

    #[Test]
    public function defaultVisibilityIsPublic(): void
    {
        $challenge = new Challenge(['title' => 'Test']);

        $this->assertSame(ChallengeVisibility::Public, $challenge->getVisibility());
    }

    #[Test]
    public function setVisibilityUpdatesVisibility(): void
    {
        $challenge = new Challenge(['title' => 'Test']);
        $challenge->setVisibility(ChallengeVisibility::Private);

        $this->assertSame(ChallengeVisibility::Private, $challenge->getVisibility());
    }

    #[Test]
    public function getUserIdReturnsUserId(): void
    {
        $challenge = new Challenge(['title' => 'Test', 'user_id' => 42]);

        $this->assertSame(42, $challenge->getUserId());
    }

    #[Test]
    public function getCategoryTidReturnsTaxonomyTermId(): void
    {
        $challenge = new Challenge(['title' => 'Test', 'category_tid' => 5]);

        $this->assertSame(5, $challenge->getCategoryTid());
    }

    #[Test]
    public function getCurrentItemIdReturnsId(): void
    {
        $challenge = new Challenge(['title' => 'Test', 'current_item_id' => 10]);

        $this->assertSame(10, $challenge->getCurrentItemId());
    }

    #[Test]
    public function getGoalItemIdReturnsId(): void
    {
        $challenge = new Challenge(['title' => 'Test', 'goal_item_id' => 20]);

        $this->assertSame(20, $challenge->getGoalItemId());
    }

    #[Test]
    public function uuidIsAutoGenerated(): void
    {
        $challenge = new Challenge(['title' => 'Test']);

        $this->assertNotEmpty($challenge->uuid());
    }

    #[Test]
    public function getDescriptionReturnsDescription(): void
    {
        $challenge = new Challenge(['title' => 'Test', 'description' => 'A fun challenge']);

        $this->assertSame('A fun challenge', $challenge->getDescription());
    }

    #[Test]
    public function getDeletedAtReturnsNullByDefault(): void
    {
        $challenge = new Challenge(['title' => 'Test']);

        $this->assertNull($challenge->getDeletedAt());
    }
}
