<?php

declare(strict_types=1);

namespace OneRedPaperclip\Tests\Unit\Entity;

use OneRedPaperclip\Entity\Notification;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

#[CoversClass(Notification::class)]
final class NotificationTest extends TestCase
{
    #[Test]
    public function entityTypeIdIsNotification(): void
    {
        $notification = new Notification([]);

        $this->assertSame('notification', $notification->getEntityTypeId());
    }

    #[Test]
    public function getUserIdReturnsUserId(): void
    {
        $notification = new Notification(['user_id' => 5]);

        $this->assertSame(5, $notification->getUserId());
    }

    #[Test]
    public function getTypeReturnsType(): void
    {
        $notification = new Notification(['type' => 'OfferAccepted']);

        $this->assertSame('OfferAccepted', $notification->getType());
    }

    #[Test]
    public function getDataReturnsDecodedArray(): void
    {
        $data = ['challenge_id' => 1, 'offer_id' => 2];
        $notification = new Notification(['data' => $data]);

        $this->assertSame($data, $notification->getData());
    }

    #[Test]
    public function isUnreadWhenReadAtIsNull(): void
    {
        $notification = new Notification([]);

        $this->assertTrue($notification->isUnread());
    }

    #[Test]
    public function isReadWhenReadAtIsSet(): void
    {
        $notification = new Notification(['read_at' => '2026-03-19 12:00:00']);

        $this->assertFalse($notification->isUnread());
    }

    #[Test]
    public function markAsReadSetsTimestamp(): void
    {
        $notification = new Notification([]);
        $notification->markAsRead('2026-03-19 12:00:00');

        $this->assertFalse($notification->isUnread());
        $this->assertSame('2026-03-19 12:00:00', $notification->getReadAt());
    }

    #[Test]
    public function uuidIsAutoGenerated(): void
    {
        $notification = new Notification([]);

        $this->assertNotEmpty($notification->uuid());
    }
}
